version: "3.9"


services:

  _base: &base
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: []
    volumes:
      - .:/code
    environment: &base-environment
      ENVIRONMENT: local
      REDIS_HOST: redis
      REDIS_PASSWORD: redis

  bot: &bot
    <<: *base
    ports:
      - "8009:8009"
    entrypoint: ['docker/start.sh']
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: redis
    volumes:
        - ./storage/redis/data:/data
  scheduler:
    <<: *base
    entrypoint: [ "docker/scheduler.sh" ]
    depends_on:
      - redis

  poetry:
    <<: *base
    entrypoint: ["poetry"]

  lint:
    <<: *base
    entrypoint: ["docker/lint.sh"]

  lint-check:
    <<: *base
    entrypoint: [ "docker/lint_check.sh" ]
