name: CI
on:
    push:
      branches: [ "master" ]

jobs:
    my_build_job:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
    
          - name: Run a one-line script
            run: |
                touch test.txt
                echo Hello, world!
    
          - name: Run a multi-line script
            run: |
                echo Add other actions to build,
                echo test, and deploy your project.
                ls -lah test.txt
    my_deploy:
      runs-on: ubuntu-latest
      environment: staging
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_USER: ${{ secrets.HOST_USER }}
          HOST_ADDRESS: ${{ secrets.HOST_ADDRESS }}
      steps:
          - uses: actions/checkout@v4
          - name: Run a multi-line deploy script
            run: |
                echo load private key
                echo '-----BEGIN OPENSSH PRIVATE KEY-----' > private_key
                echo $SSH_PRIVATE_KEY >> private_key
                echo '-----END OPENSSH PRIVATE KEY-----' >> private_key
                chmod 600 private_key
                echo Connect using ssh... 
                ssh -o StrictHostKeyChecking=no -i private_key $HOST_USER@$HOST_ADDRESS << EOF
                    cd projects/vk_copy_post_bot/
                    git pull origin master
                    docker-compose down
                    docker-compose up -d bot
                EOF

