name: Deploy
on:
    # push:
    #   branches: [ "master" ]
    workflow_dispatch:
        inputs:
          environment:
            description: 'Environment to run tests against'
            type: environment
            required: true
        
jobs:
    check-build:
      if: false
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
    
          - name: Check build docker image
            run: docker build .                
    deploy:
      runs-on: ubuntu-latest
      environment: staging
      # needs: [check-build]
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_USER: ${{ secrets.HOST_USER }}
          HOST_ADDRESS: ${{ secrets.HOST_ADDRESS }}
          CUSTOM_ENV: ${{ inputs.environment }}
      steps:
          - uses: actions/checkout@v4
          - name: Load and create private key
            run: |
                echo ENV = "$CUSTOM_ENV"
                echo '-----BEGIN OPENSSH PRIVATE KEY-----' > private_key
                echo $SSH_PRIVATE_KEY >> private_key
                echo '-----END OPENSSH PRIVATE KEY-----' >> private_key
                chmod 600 private_key
          - name: Connect to server and execute command
            run: |
                ssh -o StrictHostKeyChecking=no -i private_key $HOST_USER@$HOST_ADDRESS << EOF
                    cd projects/vk_copy_post_bot/
                    git pull origin master
                    docker-compose down
                    docker-compose up -d bot
                EOF

